# Generated by Django 4.1.13 on 2025-07-06 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AulaEstudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "estado",
                    models.CharField(
                        blank=True,
                        choices=[("activo", "Activo"), ("inactivo", "Inactivo")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("fecha_union", models.DateTimeField(auto_now_add=True)),
                ("fecha_salida", models.DateTimeField(blank=True, null=True)),
                ("fecha_inscripcion", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Estudiante en Aula",
                "verbose_name_plural": "Estudiantes en Aulas",
                "db_table": "aula_estudiantes",
            },
        ),
        migrations.CreateModel(
            name="AulaVirtual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
                ("titulo", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "codigo_acceso",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("activa", "Activa"),
                            ("inactiva", "Inactiva"),
                            ("archivada", "Archivada"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Aula Virtual",
                "verbose_name_plural": "Aulas Virtuales",
                "db_table": "aulas_virtuales",
            },
        ),
        migrations.CreateModel(
            name="InvitacionAula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("correo_invitado", models.EmailField(max_length=254)),
                ("codigo_invitacion", models.CharField(max_length=255, unique=True)),
                (
                    "estado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aceptada", "Aceptada"),
                            ("rechazada", "Rechazada"),
                            ("expirada", "Expirada"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("mensaje", models.CharField(blank=True, max_length=255, null=True)),
                ("fecha_invitacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_expiracion", models.DateTimeField()),
                ("fecha_respuesta", models.DateTimeField(blank=True, null=True)),
                (
                    "aula_virtual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aulas.aulavirtual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitación a Aula",
                "verbose_name_plural": "Invitaciones a Aulas",
                "db_table": "invitaciones_aula",
            },
        ),
    ]
