# Generated by Django 4.1.13 on 2025-07-06 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aulas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitacionaula",
            name="invitado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="aulavirtual",
            name="profesor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="aulavirtual",
            name="seccion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usuarios.seccion",
            ),
        ),
        migrations.AddField(
            model_name="aulaestudiante",
            name="aula",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="aulas.aulavirtual"
            ),
        ),
        migrations.AddField(
            model_name="aulaestudiante",
            name="estudiante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="aulaestudiante",
            name="profesor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estudiantes_inscritos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aulaestudiante",
            unique_together={("aula", "estudiante")},
        ),
    ]
