# Generated by Django 4.1.13 on 2025-07-06 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anuncio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=255)),
                ("contenido", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("anuncio", "Anuncio"),
                            ("material", "Material"),
                            ("pregunta", "Pregunta"),
                            ("evento", "Evento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("archivo_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "archivo_nombre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "archivo_tipo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("archivo_tamaño", models.BigIntegerField(blank=True, null=True)),
                ("categoria", models.CharField(blank=True, max_length=100, null=True)),
                ("etiquetas", models.JSONField(blank=True, null=True)),
                ("permite_comentarios", models.BooleanField(default=True)),
                ("total_likes", models.IntegerField(default=0)),
                ("total_comentarios", models.IntegerField(default=0)),
                ("es_recurso_academico", models.BooleanField(default=False)),
                ("fecha_publicacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_edicion", models.DateTimeField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("es_general", models.BooleanField(default=False)),
                ("fijado", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Anuncio",
                "verbose_name_plural": "Anuncios",
                "db_table": "anuncios",
                "ordering": ["-fijado", "-fecha_publicacion"],
            },
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contenido", models.TextField()),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Comentario",
                "verbose_name_plural": "Comentarios",
                "db_table": "comentarios",
                "ordering": ["fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Lectura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fecha_lectura", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Lectura",
                "verbose_name_plural": "Lecturas",
                "db_table": "lecturas",
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "anuncio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="anuncios.anuncio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Like",
                "verbose_name_plural": "Likes",
                "db_table": "likes",
            },
        ),
    ]
