# Generated by Django 4.1.13 on 2025-07-06 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("anuncios", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="anuncio",
            name="admin_censurador",
            field=models.ForeignKey(
                blank=True,
                help_text="Administrador que censuró el anuncio",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anuncios_censurados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="anuncio",
            name="censurado",
            field=models.BooleanField(
                default=False, help_text="Anuncio censurado por administrador"
            ),
        ),
        migrations.AddField(
            model_name="anuncio",
            name="fecha_censura",
            field=models.DateTimeField(
                blank=True, help_text="Fecha de censura", null=True
            ),
        ),
        migrations.AddField(
            model_name="anuncio",
            name="motivo_censura",
            field=models.TextField(
                blank=True, help_text="Motivo de la censura", null=True
            ),
        ),
    ]
