# Generated by Django 5.2.4 on 2025-07-07 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anuncios", "0003_add_admin_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anuncio",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="anuncio",
            name="updated_at",
        ),
    ]
