# Generated by Django 5.2.4 on 2025-07-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anuncios", "0004_remove_anuncio_created_at_remove_anuncio_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anuncio",
            name="fijado",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
