# Generated by Django 5.2.4 on 2025-07-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_add_admin_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seccion",
            name="ciclo",
            field=models.IntegerField(db_column="ciclo"),
        ),
    ]
