# Generated by Django 4.1.13 on 2025-07-06 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anuncios", "0003_add_admin_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("clave", models.CharField(max_length=100, unique=True)),
                ("valor", models.TextField()),
                ("descripcion", models.TextField(blank=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("entero", "Entero"),
                            ("decimal", "Decimal"),
                            ("texto", "Texto"),
                            ("booleano", "Booleano"),
                            ("json", "JSON"),
                        ],
                        default="texto",
                        max_length=20,
                    ),
                ),
                ("categoria", models.CharField(default="general", max_length=50)),
                ("es_publica", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Configuración del Sistema",
                "verbose_name_plural": "Configuraciones del Sistema",
                "db_table": "configuracion_sistema",
            },
        ),
        migrations.CreateModel(
            name="LogModeración",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("censurar_anuncio", "Censurar Anuncio"),
                            ("descensurar_anuncio", "Descensurar Anuncio"),
                            ("strike_usuario", "Aplicar Strike a Usuario"),
                            ("suspender_usuario", "Suspender Usuario"),
                            ("reactivar_usuario", "Reactivar Usuario"),
                            ("crear_profesor", "Crear Profesor"),
                            ("eliminar_anuncio", "Eliminar Anuncio"),
                            ("advertencia_usuario", "Advertencia a Usuario"),
                        ],
                        max_length=30,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("motivo", models.TextField(blank=True, null=True)),
                ("datos_adicionales", models.JSONField(blank=True, null=True)),
                (
                    "administrador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acciones_moderacion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "anuncio_afectado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anuncios.anuncio",
                    ),
                ),
                (
                    "usuario_afectado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs_recibidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Moderación",
                "verbose_name_plural": "Logs de Moderación",
                "db_table": "logs_moderacion",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EstadisticasSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fecha", models.DateField()),
                ("tipo_estadistica", models.CharField(max_length=50)),
                ("categoria", models.CharField(max_length=50)),
                ("valor", models.IntegerField()),
                (
                    "valor_decimal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Estadística del Sistema",
                "verbose_name_plural": "Estadísticas del Sistema",
                "db_table": "estadisticas_sistema",
                "unique_together": {("fecha", "tipo_estadistica", "categoria")},
            },
        ),
    ]
