# Generated by Django 5.2.4 on 2025-07-07 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0001_initial_admin_models"),
        ("anuncios", "0004_remove_anuncio_created_at_remove_anuncio_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialModeracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion", models.CharField(max_length=50)),
                ("comentario", models.TextField(blank=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "anuncio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_moderacion",
                        to="anuncios.anuncio",
                    ),
                ),
                (
                    "moderador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LogModeracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("censurar_anuncio", "Censurar Anuncio"),
                            ("descensurar_anuncio", "Descensurar Anuncio"),
                            ("strike_usuario", "Aplicar Strike a Usuario"),
                            ("suspender_usuario", "Suspender Usuario"),
                            ("reactivar_usuario", "Reactivar Usuario"),
                            ("crear_profesor", "Crear Profesor"),
                            ("eliminar_anuncio", "Eliminar Anuncio"),
                            ("advertencia_usuario", "Advertencia a Usuario"),
                        ],
                        max_length=30,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("motivo", models.TextField(blank=True, null=True)),
                ("datos_adicionales", models.JSONField(blank=True, null=True)),
                (
                    "administrador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acciones_moderacion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "anuncio_afectado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anuncios.anuncio",
                    ),
                ),
                (
                    "usuario_afectado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs_recibidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Moderación",
                "verbose_name_plural": "Logs de Moderación",
                "db_table": "logs_moderacion",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="LogModeración",
        ),
    ]
