# Generated by Django 4.1.13 on 2025-07-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="activo",
            field=models.BooleanField(
                default=True, help_text="Usuario activo (no suspendido)"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="fecha_suspension",
            field=models.DateTimeField(
                blank=True, help_text="Fecha hasta cuando está suspendido", null=True
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="motivo_suspension",
            field=models.TextField(
                blank=True, help_text="Motivo de la suspensión", null=True
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="strikes",
            field=models.IntegerField(
                default=0, help_text="Número de strikes acumulados"
            ),
        ),
    ]
