spring.security.oauth2.client.registration.google.client-id=cambiar
spring.security.oauth2.client.registration.google.client-secret=cambiar
spring.security.oauth2.client.registration.google.redirect-uri=https://22ac-2800-200-e810-55b-9d09-ae3c-3f47-8ec2.ngrok-free.app/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=name

# Configura la restricción de dominio (opcional, pero recomendado)
spring.security.oauth2.client.registration.google.client-settings.user-info-endpoint.additional-parameters.hd=tecsup.edu.pe

server.port=8081

# Configuración de CORS
spring.web.cors.allowed-origins=http://localhost:5173 # La URL de tu frontend de React
spring.web.cors.allowed-methods=*
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true